# Labirary

In [1]:
import numpy as np

In [2]:
L=[1,2,3,4,5,6,7,8]

In [3]:
A1=np.array(L)
print(A1)
type(A1)

[1 2 3 4 5 6 7 8]


numpy.ndarray

In [4]:
a2=np.arange(10)
print(a2)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
a2.size

10

In [25]:
a2.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
A1= np.random.randint(1,20,size=(6,4))
A1

array([[ 9,  2,  4, 14],
       [ 7, 16,  6, 16],
       [ 2,  1, 16, 14],
       [ 2, 15, 18, 14],
       [12, 19,  2, 11],
       [ 2, 14, 14,  4]], dtype=int32)

In [16]:
A1.shape

(6, 4)

In [17]:
A1[0] # row

array([ 9,  2,  4, 14], dtype=int32)

In [18]:
A1[0,0]

np.int32(9)

In [19]:
A1[:,0]     # cloumns

array([ 9,  7,  2,  2, 12,  2], dtype=int32)

In [21]:
A1[0:2,0:2]

array([[ 9,  2],
       [ 7, 16]], dtype=int32)

In [22]:
A1

array([[ 9,  2,  4, 14],
       [ 7, 16,  6, 16],
       [ 2,  1, 16, 14],
       [ 2, 15, 18, 14],
       [12, 19,  2, 11],
       [ 2, 14, 14,  4]], dtype=int32)

In [25]:
A1[3:5,1:3]

array([[15, 18],
       [19,  2]], dtype=int32)

In [29]:
A1[1:6:2,1:4:2]

array([[16, 16],
       [15, 14],
       [14,  4]], dtype=int32)

In [34]:
A1[0:4:3,0:3:2]

array([[ 9,  4],
       [ 2, 18]], dtype=int32)

# Filter

In [35]:
A1<10

array([[ True,  True,  True, False],
       [ True, False,  True, False],
       [ True,  True, False, False],
       [ True, False, False, False],
       [False, False,  True, False],
       [ True, False, False,  True]])

In [36]:
A1[A1<10]

array([9, 2, 4, 7, 6, 2, 1, 2, 2, 2, 4], dtype=int32)

In [39]:
A1[A1==10]

array([], dtype=int32)

In [40]:
A1[A1%2==0]

array([ 2,  4, 14, 16,  6, 16,  2, 16, 14,  2, 18, 14, 12,  2,  2, 14, 14,
        4], dtype=int32)

In [41]:
A1[A1%2!=0]

array([ 9,  7,  1, 15, 19, 11], dtype=int32)